### PR TITLE
Fix casing of `mib` vs `MiB`

### LINKED ISSUE #25: Incorrectly cased 'size_mib' attribute in Hardware::Memory
In https://github.com/vmware/vsphere-automation-sdk-ruby/blob/master/client/sdk/com/vmware/vcenter/vm/hardware.rb (Memory Class) , the size_mib is incorrectly cased resulting in error
 
 Memory Configurations of a VM: undefined method `size_MiB_=' for #<Com::Vmware::Vcenter::Vm::Hardware::Memory::Info:0x00000003a8fe28>
Did you mean?  size_mib=
               size_mib (NoMethodError)

This is similar to https://github.com/vmware/vsphere-automation-sdk-ruby/issues/11 , but in a different file

### PR DESCRIPTION
**Pull request by jrgarcia**
In several places, the incorrect casing of `mib` was used instead of
`MiB`. The binding generator generates this incorrectly and this was
caused when generating the 6.6.1 bindings. This was reported in #25.

Fixes #25

Signed-off-by: J.R. Garcia <jrg@vmware.com>

### CODE REVIEW

File: client/sdk/com/vmware/vcenter/vm/hardware.rb [hunk 1]
```diff
@@ -3994,9 +3994,9 @@ def binding_type
         end
       end
 
-      attr_accessor :size_mib,
+      attr_accessor :size_MiB,
                     :hot_add_enabled,
-                    :hot_add_increment_size_mib,
+                    :hot_add_increment_size_MiB,
                     :hot_add_limit_mib
```
Comment (jobingeo) [inline client/sdk/com/vmware/vcenter/vm/hardware.rb]: Incorrect casing noted here. Please change in lieu of line 3988, if required

File: client/sdk/com/vmware/vcenter/vm/hardware.rb [hunk 2]
```diff
@@ -4008,13 +4008,13 @@ def initialize(ruby_values = nil, struct_value = nil)
...
-    # @!attribute [rw] size_mib
+    # @!attribute [rw] size_MiB
     #     @return [Fixnum, nil]
     #     New memory size in mebibytes.  
     #     
     #      The supported range of memory sizes is constrained by the configured guest operating system and virtual hardware version of the virtual machine.  
     #     
-    #      If the virtual machine is running, this value may only be changed if   :attr:`Com::Vmware::Vcenter::Vm::Hardware::Memory::Info.hot_add_enabled`   is true, and the new memory size must satisfy the constraints specified by   :attr:`Com::Vmware::Vcenter::Vm::Hardware::Memory::Info.hot_add_increment_size_mib`   and   :attr:`Com::Vmware::Vcenter::Vm::Hardware::Memory::Info.hot_add_limit_mib`  .
+    #      If the virtual machine is running, this value may only be changed if   :attr:`Com::Vmware::Vcenter::Vm::Hardware::Memory::Info.hot_add_enabled`   is true, and the new memory size must satisfy the constraints specified by   :attr:`Com::Vmware::Vcenter::Vm::Hardware::Memory::Info.hot_add_increment_size_MiB`   and   :attr:`Com::Vmware::Vcenter::Vm::Hardware::Memory::Info.hot_add_limit_mib`  .
```
Comment (jobingeo) [inline client/sdk/com/vmware/vcenter/vm/hardware.rb]: 'hot_add_limit_mib' needs to be correctly cased in lieu of line 3988/4000
